### PR TITLE
Support ESLint v9

### LINKED ISSUE #57: Add ESLint 9 support
Right now we have this error:

```
npx eslint .

Oops! Something went wrong! :(

ESLint: 9.0.0

TypeError: context.getScope is not a function
Occurred while linting /home/ai/Dev/logux-eslint-config/demo/test.js:5
Rule: "prefer-let/prefer-let"
    at isGlobalScope (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint-plugin-prefer-let@3.0.1/node_modules/eslint-plugin-prefer-let/lib/rules/prefer-let.js:32:22)
    at isTopLevelScope (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint-plugin-prefer-let@3.0.1/node_modules/eslint-plugin-prefer-let/lib/rules/prefer-let.js:44:14)
    at VariableDeclaration (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint-plugin-prefer-let@3.0.1/node_modules/eslint-plugin-prefer-let/lib/rules/prefer-let.js:58:44)
    at ruleErrorHandler (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/linter.js:1145:48)
    at /home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/ai/Dev/logux-eslint-config/node_modules/.pnpm/eslint@9.0.0/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

### PR DESCRIPTION
**Pull request by azat-io**
Close #57

### CODE REVIEW

**Comment by azat-io** [comment]
@cowboyd Thanks!
Let's make a new release of eslint-plugin-prefer-let?

**Comment by cowboyd** [comment]
@jbolda @wKich It looks like this never did get released. Do we need to migrate to covector? 

https://github.com/thefrontside/javascript/actions/runs/9304386082/job/25608824913

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/thefrontside/javascript">Merge pull request #60 from azat-io/feat/eslint-9 · thefrontside/javascript@1717088</a></strong></div><div>Frontside JavaScript tooling. Contribute to thefrontside/javascript development by creating an account on GitHub.</div></blockquote>

**Comment by jbolda** [comment]
@azat-io This has been published.
https://www.npmjs.com/package/eslint-plugin-prefer-let/v/4.0.0

**Comment by azat-io** [comment]
@jbolda Thanks!

**Pull request merged**
